---

- name: reenable pushprox service
  command: systemctl reenable prometheus-pushprox.service

- name: reinit pushprox
  command: initctl reload-configuration

- name: restart pushprox
  service:
    name: prometheus-pushprox
    state: restarted
